### ISSUE TITLE
Help Needed 

### ISSUE THREAD

**Issue by eshaanagarwal** [AbhishekRS4/fcn_road_seg#1]
Hi ! I was following your code in order to try implementing FCN for road segmentation . I actually needed to test out results on a custom image ! Can you please guide me with how to do that ?

**Comment by AbhishekRS4** [comment]
Once you have trained the model using fcn_train.py, you can use fcn_infer.py to test the model on custom images. All these images have to be in a directory. You can take a look at fcn_config.json. There is an entry named "inouts_path". This is being used for training as well as during testing which is a bit misleading. They have to be different. You can add an entry for test set in fcn_config.json and change it accordingly in the fcn_infer.py

Hope this helps!!
